# fly.toml app configuration file generated for klangwerk-berlin on 2025-02-09T06:43:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'klangwerk-berlin'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
